#!/usr/bin/env python3
"""
🚀 miniZ MCP - Professional EXE Builder
Build file EXE cho khách hàng với:
- Mã hóa API keys
- Không lộ thông tin nhạy cảm
- Tự động cài đặt dependencies
- Tạo shortcut và startup
"""

import os
import sys
import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime

# ============================================================
# CONFIGURATION
# ============================================================

APP_NAME = "miniZ_MCP"
APP_VERSION = "4.3.0"
APP_AUTHOR = "miniZ Team"
APP_DESCRIPTION = "miniZ MCP - Điều khiển máy tính bằng AI"

BASE_DIR = Path(__file__).parent.resolve()
DIST_DIR = BASE_DIR / "dist"
BUILD_DIR = BASE_DIR / "build"
OUTPUT_DIR = BASE_DIR / "output"

# Files to exclude from build (sensitive)
EXCLUDE_FILES = [
    "xiaozhi_endpoints.json",  # Contains API keys
    "rag_cache.json",
    "*.pyc",
    "__pycache__",
    ".git",
    ".vscode",
    "*.log",
    "build",
    "dist",
    "output",
]

# Files to include in build
INCLUDE_FILES = [
    "xiaozhi_final.py",
    "rag_system.py",
    "rag_config.json",
    "security_module.py",
    "startup_manager.py",
    "tray_app.py",
    "requirements.txt",
    "music_library",
]

# ============================================================
# PYINSTALLER SPEC TEMPLATE
# ============================================================

SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
"""
miniZ MCP PyInstaller Spec
Auto-generated by build_exe_pro.py
"""

import sys
from pathlib import Path

block_cipher = None

# Main analysis
a = Analysis(
    ['{main_script}'],
    pathex=['{base_dir}'],
    binaries=[],
    datas=[
        ('rag_system.py', '.'),
        ('rag_config.json', '.'),
        ('security_module.py', '.'),
        ('startup_manager.py', '.'),
        ('music_library', 'music_library'),
    ],
    hiddenimports=[
        # FastAPI & Web
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.responses',
        'fastapi.staticfiles',
        'starlette',
        'starlette.responses',
        'pydantic',
        'pydantic_core',
        'websockets',
        'websockets.client',
        'aiohttp',
        'httpx',
        
        # System control
        'psutil',
        'pyautogui',
        'pynput',
        'pynput.keyboard',
        'pynput.mouse',
        'screen_brightness_control',
        'pycaw',
        'pycaw.pycaw',
        'comtypes',
        'comtypes.client',
        
        # Windows
        'wmi',
        'pythoncom',
        'win32com',
        'win32com.client',
        'win32api',
        'win32gui',
        'win32con',
        'winreg',
        'ctypes',
        'ctypes.wintypes',
        
        # AI APIs
        'google.generativeai',
        'google.ai',
        'openai',
        
        # Search & RAG
        'duckduckgo_search',
        'duckduckgo_search.duckduckgo_search',
        'bs4',
        'beautifulsoup4',
        
        # VLC
        'vlc',
        
        # Tray
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        
        # Encoding
        'encodings',
        'encodings.utf_8',
        'encodings.ascii',
        'encodings.latin_1',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{app_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={console},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='{icon_file}' if Path('{icon_file}').exists() else None,
    version='{version_file}' if Path('{version_file}').exists() else None,
)
'''

# ============================================================
# VERSION INFO TEMPLATE
# ============================================================

VERSION_TEMPLATE = '''# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'{author}'),
            StringStruct(u'FileDescription', u'{description}'),
            StringStruct(u'FileVersion', u'{version}'),
            StringStruct(u'InternalName', u'{app_name}'),
            StringStruct(u'LegalCopyright', u'Copyright (c) 2024-2025 {author}'),
            StringStruct(u'OriginalFilename', u'{app_name}.exe'),
            StringStruct(u'ProductName', u'{app_name}'),
            StringStruct(u'ProductVersion', u'{version}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def print_header(text: str):
    """Print formatted header"""
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}")

def print_step(step: int, total: int, text: str):
    """Print step progress"""
    print(f"\n[{step}/{total}] {text}")

def run_command(cmd: list, cwd: Path = None) -> bool:
    """Run command and return success status"""
    try:
        result = subprocess.run(
            cmd,
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            print(f"  ❌ Error: {result.stderr}")
            return False
        return True
    except Exception as e:
        print(f"  ❌ Exception: {e}")
        return False

def check_dependencies() -> bool:
    """Check and install required packages"""
    print_step(1, 5, "Kiểm tra dependencies...")
    
    required = ['pyinstaller', 'pystray', 'Pillow']
    missing = []
    
    for pkg in required:
        try:
            __import__(pkg.lower().replace('-', '_'))
            print(f"  ✅ {pkg}")
        except ImportError:
            missing.append(pkg)
            print(f"  ❌ {pkg} (missing)")
    
    if missing:
        print(f"\n  📦 Installing: {', '.join(missing)}")
        subprocess.run([
            sys.executable, '-m', 'pip', 'install',
            '--quiet', '--upgrade'
        ] + missing)
    
    return True

def create_version_file() -> Path:
    """Create version info file for Windows"""
    print("  📝 Creating version info...")
    
    version_parts = APP_VERSION.split('.')
    while len(version_parts) < 4:
        version_parts.append('0')
    version_tuple = tuple(int(v) for v in version_parts[:4])
    
    content = VERSION_TEMPLATE.format(
        version_tuple=version_tuple,
        author=APP_AUTHOR,
        description=APP_DESCRIPTION,
        version=APP_VERSION,
        app_name=APP_NAME
    )
    
    version_file = BASE_DIR / "version_info.py"
    version_file.write_text(content, encoding='utf-8')
    
    return version_file

def create_spec_file(console_mode: bool = False) -> Path:
    """Create PyInstaller spec file"""
    print("  📝 Creating spec file...")
    
    main_script = "tray_app.py" if not console_mode else "xiaozhi_final.py"
    icon_file = BASE_DIR / "miniz_icon.ico"
    version_file = BASE_DIR / "version_info.py"
    
    content = SPEC_TEMPLATE.format(
        main_script=main_script,
        base_dir=str(BASE_DIR).replace('\\', '/'),
        app_name=APP_NAME,
        console='False' if not console_mode else 'True',
        icon_file=str(icon_file).replace('\\', '/'),
        version_file=str(version_file).replace('\\', '/')
    )
    
    spec_file = BASE_DIR / f"{APP_NAME}.spec"
    spec_file.write_text(content, encoding='utf-8')
    
    return spec_file

def create_default_config() -> Path:
    """Create default config without API keys"""
    print("  📝 Creating default config...")
    
    config = {
        "endpoints": [
            {"name": "Thiết bị 1", "token": "", "enabled": False},
            {"name": "Thiết bị 2", "token": "", "enabled": False},
            {"name": "Thiết bị 3", "token": "", "enabled": False}
        ],
        "active_index": 0,
        "gemini_api_key": "",
        "openai_api_key": "",
        "serper_api_key": "",
        "_note": "API keys sẽ được nhập trong giao diện Settings",
        "last_updated": datetime.now().isoformat()
    }
    
    config_file = BASE_DIR / "xiaozhi_endpoints_template.json"
    with open(config_file, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
    
    return config_file

def build_exe(console_mode: bool = False) -> bool:
    """Build EXE with PyInstaller"""
    print_step(2, 5, "Building EXE với PyInstaller...")
    
    # Create spec file
    spec_file = create_spec_file(console_mode)
    create_version_file()
    
    # Clean previous builds (skip if locked)
    if DIST_DIR.exists():
        try:
            shutil.rmtree(DIST_DIR)
        except PermissionError:
            print("  ⚠️  Warning: dist folder is locked, skipping cleanup")
            # Try to clean EXE only
            exe_file = DIST_DIR / f"{APP_NAME}.exe"
            if exe_file.exists():
                try:
                    exe_file.unlink()
                except:
                    print(f"  ⚠️  Warning: Cannot delete {APP_NAME}.exe, will overwrite")
    
    if BUILD_DIR.exists():
        try:
            shutil.rmtree(BUILD_DIR)
        except PermissionError:
            print("  ⚠️  Warning: build folder is locked, skipping cleanup")
    
    # Run PyInstaller
    cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--clean',
        '--noconfirm',
        str(spec_file)
    ]
    
    print(f"  🔨 Running: pyinstaller {spec_file.name}")
    
    result = subprocess.run(
        cmd,
        cwd=str(BASE_DIR),
        capture_output=False
    )
    
    if result.returncode != 0:
        print("  ❌ PyInstaller failed!")
        return False
    
    # Check output
    exe_path = DIST_DIR / f"{APP_NAME}.exe"
    if exe_path.exists():
        size_mb = exe_path.stat().st_size / (1024 * 1024)
        print(f"  ✅ EXE created: {exe_path.name} ({size_mb:.1f} MB)")
        return True
    else:
        print("  ❌ EXE not found!")
        return False

def create_installer_package() -> Path:
    """Create complete installer package"""
    print_step(3, 5, "Tạo package cài đặt...")
    
    # Create output directory
    OUTPUT_DIR.mkdir(exist_ok=True)
    
    package_name = f"{APP_NAME}_v{APP_VERSION}_Setup"
    package_dir = OUTPUT_DIR / package_name
    
    if package_dir.exists():
        shutil.rmtree(package_dir)
    package_dir.mkdir()
    
    # Copy EXE
    exe_src = DIST_DIR / f"{APP_NAME}.exe"
    if exe_src.exists():
        shutil.copy(exe_src, package_dir / f"{APP_NAME}.exe")
        print(f"  ✅ Copied: {APP_NAME}.exe")
    
    # Create default config (no API keys)
    config_template = create_default_config()
    shutil.copy(config_template, package_dir / "xiaozhi_endpoints.json")
    print(f"  ✅ Created: xiaozhi_endpoints.json (empty)")
    
    # Copy rag_config.json (without serper key)
    rag_config_src = BASE_DIR / "rag_config.json"
    if rag_config_src.exists():
        with open(rag_config_src, 'r', encoding='utf-8') as f:
            rag_config = json.load(f)
        # Remove sensitive data
        rag_config.pop('serper_api_key', None)
        rag_config['serper_api_key'] = ""
        with open(package_dir / "rag_config.json", 'w', encoding='utf-8') as f:
            json.dump(rag_config, f, indent=2, ensure_ascii=False)
        print(f"  ✅ Created: rag_config.json (cleaned)")
    
    # Copy music_library structure
    music_src = BASE_DIR / "music_library"
    if music_src.exists():
        shutil.copytree(music_src, package_dir / "music_library")
        print(f"  ✅ Copied: music_library/")
    
    # Create README for customer
    readme_content = f"""
╔══════════════════════════════════════════════════════════╗
║         🚀 miniZ MCP v{APP_VERSION} - Installation Guide          ║
╚══════════════════════════════════════════════════════════╝

📁 CẤU TRÚC THƯ MỤC:
    {APP_NAME}.exe          - Ứng dụng chính
    xiaozhi_endpoints.json  - File cấu hình
    rag_config.json         - Cấu hình RAG search
    music_library/          - Thư mục nhạc mẫu

🚀 HƯỚNG DẪN CÀI ĐẶT:

1. CHẠY ỨNG DỤNG
   - Double-click vào {APP_NAME}.exe
   - Lần đầu có thể mất 10-30 giây để khởi động
   - Browser sẽ tự động mở tại http://localhost:8000

2. CẤU HÌNH API KEYS
   - Click vào icon ⚙️ Settings ở góc phải
   - Nhập Gemini API Key (miễn phí tại aistudio.google.com)
   - Nhập Serper API Key (miễn phí tại serper.dev)
   - Các keys sẽ được lưu tự động

3. KẾT NỐI XIAOZHI ROBOT
   - Copy MCP Token từ app Xiaozhi
   - Paste vào ô Token trong Settings
   - Click "Kết Nối"

4. KHỞI ĐỘNG CÙNG WINDOWS (tùy chọn)
   - Right-click vào icon trong System Tray
   - Chọn "Khởi động cùng Windows"

⚠️ LƯU Ý:
- Không chia sẻ API keys với người khác
- Backup file xiaozhi_endpoints.json khi cần

📞 HỖ TRỢ:
- Email: support@miniz.vn
- GitHub: github.com/miniZ-MCP

============================================================
         Copyright © 2024-2025 miniZ Team
============================================================
"""
    
    (package_dir / "README.txt").write_text(readme_content, encoding='utf-8')
    print(f"  ✅ Created: README.txt")
    
    # Create install batch file
    install_bat = f"""@echo off
chcp 65001 >nul
title 🚀 miniZ MCP - Cài Đặt

echo.
echo ╔══════════════════════════════════════════════════════════╗
echo ║         🚀 miniZ MCP v{APP_VERSION} - Cài Đặt                    ║
echo ╚══════════════════════════════════════════════════════════╝
echo.

:: Check if running as admin
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo ⚠️  Đang chạy với quyền Administrator...
    powershell -Command "Start-Process '%~f0' -Verb RunAs"
    exit /b
)

:: Get install path
set INSTALL_PATH=%LOCALAPPDATA%\\miniZ_MCP

echo 📁 Thư mục cài đặt: %INSTALL_PATH%
echo.

:: Create directory
if not exist "%INSTALL_PATH%" mkdir "%INSTALL_PATH%"

:: Copy files
echo 📦 Đang sao chép files...
xcopy /E /Y /Q "%~dp0*" "%INSTALL_PATH%\\" >nul

:: Create desktop shortcut
echo 🔗 Tạo shortcut Desktop...
powershell -Command "$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('%USERPROFILE%\\Desktop\\miniZ MCP.lnk'); $s.TargetPath = '%INSTALL_PATH%\\{APP_NAME}.exe'; $s.WorkingDirectory = '%INSTALL_PATH%'; $s.Description = 'miniZ MCP - AI Control'; $s.Save()"

:: Create Start Menu shortcut
echo 🔗 Tạo shortcut Start Menu...
set STARTMENU=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\miniZ MCP
if not exist "%STARTMENU%" mkdir "%STARTMENU%"
powershell -Command "$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('%STARTMENU%\\miniZ MCP.lnk'); $s.TargetPath = '%INSTALL_PATH%\\{APP_NAME}.exe'; $s.WorkingDirectory = '%INSTALL_PATH%'; $s.Save()"

echo.
echo ✅ Cài đặt hoàn tất!
echo.
echo 🚀 Bạn có muốn chạy miniZ MCP ngay? (Y/N)
set /p RUN=

if /i "%RUN%"=="Y" (
    start "" "%INSTALL_PATH%\\{APP_NAME}.exe"
)

echo.
echo 👋 Nhấn phím bất kỳ để đóng...
pause >nul
"""
    
    (package_dir / "INSTALL.bat").write_text(install_bat, encoding='utf-8')
    print(f"  ✅ Created: INSTALL.bat")
    
    # Create uninstall batch
    uninstall_bat = f"""@echo off
chcp 65001 >nul
title 🗑️ miniZ MCP - Gỡ Cài Đặt

echo.
echo ╔══════════════════════════════════════════════════════════╗
echo ║         🗑️ miniZ MCP - Gỡ Cài Đặt                        ║
echo ╚══════════════════════════════════════════════════════════╝
echo.

set INSTALL_PATH=%LOCALAPPDATA%\\miniZ_MCP

echo ⚠️  Bạn có chắc muốn gỡ cài đặt miniZ MCP? (Y/N)
set /p CONFIRM=

if /i not "%CONFIRM%"=="Y" (
    echo Đã hủy.
    pause
    exit /b
)

:: Kill running process
taskkill /F /IM {APP_NAME}.exe 2>nul

:: Remove from startup
reg delete "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v "miniZ_MCP" /f 2>nul

:: Remove shortcuts
del /f /q "%USERPROFILE%\\Desktop\\miniZ MCP.lnk" 2>nul
rmdir /s /q "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\miniZ MCP" 2>nul

:: Remove install directory
rmdir /s /q "%INSTALL_PATH%" 2>nul

echo.
echo ✅ Đã gỡ cài đặt miniZ MCP!
echo.
pause
"""
    
    (package_dir / "UNINSTALL.bat").write_text(uninstall_bat, encoding='utf-8')
    print(f"  ✅ Created: UNINSTALL.bat")
    
    return package_dir

def create_zip_package(package_dir: Path) -> Path:
    """Create ZIP archive of package"""
    print_step(4, 5, "Tạo file ZIP...")
    
    zip_name = f"{package_dir.name}"
    zip_path = OUTPUT_DIR / zip_name
    
    # Remove old zip if exists
    if Path(f"{zip_path}.zip").exists():
        Path(f"{zip_path}.zip").unlink()
    
    shutil.make_archive(str(zip_path), 'zip', OUTPUT_DIR, package_dir.name)
    
    zip_file = Path(f"{zip_path}.zip")
    if zip_file.exists():
        size_mb = zip_file.stat().st_size / (1024 * 1024)
        print(f"  ✅ Created: {zip_file.name} ({size_mb:.1f} MB)")
        return zip_file
    
    return None

def cleanup():
    """Clean up temporary files"""
    print_step(5, 5, "Dọn dẹp...")
    
    # Remove build directory
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
        print(f"  🗑️ Removed: build/")
    
    # Remove spec file
    spec_file = BASE_DIR / f"{APP_NAME}.spec"
    if spec_file.exists():
        spec_file.unlink()
        print(f"  🗑️ Removed: {spec_file.name}")
    
    # Remove version file
    version_file = BASE_DIR / "version_info.py"
    if version_file.exists():
        version_file.unlink()
        print(f"  🗑️ Removed: version_info.py")

# ============================================================
# MAIN
# ============================================================

def main():
    """Main build process"""
    print("""
╔══════════════════════════════════════════════════════════╗
║    🚀 miniZ MCP - Professional EXE Builder v4.3.0       ║
╠══════════════════════════════════════════════════════════╣
║  Build file EXE cho khách hàng:                          ║
║  ✅ Không lộ API keys                                    ║
║  ✅ Mã hóa thông tin nhạy cảm                            ║
║  ✅ Tự động tạo shortcut                                 ║
║  ✅ Hỗ trợ khởi động cùng Windows                        ║
╚══════════════════════════════════════════════════════════╝
    """)
    
    try:
        # Step 1: Check dependencies
        check_dependencies()
        
        # Step 2: Build EXE
        if not build_exe(console_mode=False):
            print("\n❌ Build failed!")
            return 1
        
        # Step 3: Create package
        package_dir = create_installer_package()
        
        # Step 4: Create ZIP
        zip_file = create_zip_package(package_dir)
        
        # Step 5: Cleanup
        cleanup()
        
        # Summary
        print(f"""
╔══════════════════════════════════════════════════════════╗
║                   ✅ BUILD THÀNH CÔNG!                   ║
╠══════════════════════════════════════════════════════════╣
║  📁 Output Directory: {str(OUTPUT_DIR)[:35]}...
║                                                          ║
║  📦 Files đã tạo:                                        ║
║     • {package_dir.name}/                  ║
║       ├── {APP_NAME}.exe                            ║
║       ├── xiaozhi_endpoints.json (empty)                 ║
║       ├── rag_config.json (cleaned)                      ║
║       ├── INSTALL.bat                                    ║
║       ├── UNINSTALL.bat                                  ║
║       └── README.txt                                     ║
║                                                          ║
║     • {zip_file.name if zip_file else 'N/A'}             ║
║                                                          ║
║  🔐 Bảo mật:                                             ║
║     ✅ Không chứa API keys                               ║
║     ✅ Config template trống                             ║
║     ✅ Keys mã hóa khi user nhập                         ║
╚══════════════════════════════════════════════════════════╝
        """)
        
        # Open output folder
        os.startfile(str(OUTPUT_DIR))
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    sys.exit(main())
